export const LOGIN = "LOGIN";
export const FETCH_USER = "FETCH_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";
export const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";
export const ADD_USER_FULFILLED = "ADD_USER_FULFILLED";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
export const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";
export const FETCH_RESOURCE_CENTER_FULFILLED =
    "FETCH_RESOURCE_CENTER_FULFILLED";
export const FETCH_RESOURCE_CENTER_REJECTED = "FETCH_RESOURCE_CENTER_REJECTED";
export const ADD_RESOURCE_CENTER_FULFILLED = "ADD_RESOURCE_CENTER_FULFILLED";
export const ADD_RESOURCE_CENTER_REJECTED = "ADD_RESOURCE_CENTER_REJECTED";
export const ADD_RESOURCE_CENTER = "ADD_RESOURCE_CENTER";
export const DELETE_RESOURCE_CENTER = "DELETE_RESOURCE_CENTER";
export const UPDATE_RESOURCE_CENTER = "UPDATE_RESOURCE_CENTER";
export const FETCH_RESOURCE_CENTER = "FETCH_RESOURCE_CENTER";
export const UPDATE_RESOURCE_CENTER_FULFILLED =
    "UPDATE_RESOURCE_CENTER_FULFILLED";
export const UPDATE_RESOURCE_CENTER_REJECTED =
    "UPDATE_RESOURCE_CENTER_REJECTED";
export const DELETE_RESOURCE_CENTER_FULFILLED =
    "DELETE_RESOURCE_CENTER_FULFILLED";
export const DELETE_RESOURCE_CENTER_REJECTED =
    "DELETE_RESOURCE_CENTER_REJECTED";
export const SHOW_RESOURCE_CENTER_VIEWLIST = "SHOW_RESOURCE_CENTER_VIEWLIST";
export const ADD_QUESTION_BANK = "ADD_QUESTION_BANK";
export const DELETE_QUESTION_BANK = "DELETE_QUESTION_BANK";
export const UPDATE_QUESTION_BANK = "UPDATE_QUESTION_BANK";
export const FETCH_QUESTION_BANK = "FETCH_QUESTION_BANK";
export const ADD_QUESTION_BANK_FULFILLED = "ADD_QUESTION_BANK_FULFILLED";
export const ADD_QUESTION_BANK_REJECTED = "ADD_QUESTION_BANK_REJECTED";
export const UPDATE_QUESTION_BANK_FULFILLED = "UPDATE_QUESTION_BANK_FULFILLED";
export const UPDATE_QUESTION_BANK_REJECTED = "UPDATE_QUESTION_BANK_REJECTED";
export const DELETE_QUESTION_BANK_FULFILLED = "DELETE_QUESTION_BANK_FULFILLED";
export const DELETE_QUESTION_BANK_REJECTED = "DELETE_QUESTION_BANK_REJECTED";
export const FETCH_QUESTION_BANK_FULFILLED = "FETCH_QUESTION_BANK_FULFILLED";
export const FETCH_QUESTION_BANK_REJECTED = "FETCH_QUESTION_BANK_REJECTED";
export const ADD_FILTER_CRITERIA = "ADD_FILTER_CRITERIA";
export const DELETE_FILTER_CRITERIA = "DELETE_FILTER_CRITERIA";
export const UPDATE_FILTER_CRITERIA = "UPDATE_FILTER_CRITERIA";
export const FETCH_FILTER_CRITERIA = "FETCH_FILTER_CRITERIA";
export const ADD_FILTER_CRITERIA_FULFILLED = "ADD_FILTER_CRITERIA_FULFILLED";
export const ADD_FILTER_CRITERIA_REJECTED = "ADD_FILTER_CRITERIA_REJECTED";
export const UPDATE_FILTER_CRITERIA_FULFILLED =
    "UPDATE_FILTER_CRITERIA_FULFILLED";
export const UPDATE_FILTER_CRITERIA_REJECTED =
    "UPDATE_FILTER_CRITERIA_REJECTED";
export const DELETE_FILTER_CRITERIA_FULFILLED =
    "DELETE_FILTER_CRITERIA_FULFILLED";
export const DELETE_FILTER_CRITERIA_REJECTED =
    "DELETE_FILTER_CRITERIA_REJECTED";
export const FETCH_FILTER_CRITERIA_FULFILLED =
    "FETCH_FILTER_CRITERIA_FULFILLED";
export const FETCH_FILTER_CRITERIA_REJECTED = "FETCH_FILTER_CRITERIA_REJECTED";
export const SET_EDITABLE_FILTER_CRITERIA = "SET_EDITABLE_FILTER_CRITERIA";
export const TOGGLE_FORM = "TOGGLE_FORM";
export const SAVE_FILEDATA_TO_DB = "SAVE_FILEDATA_TO_DB";
export const SAVE_FILEDATA_TO_DB_FULFILLED = "SAVE_FILEDATA_TO_DB_FULFILLED";
export const SAVE_FILEDATA_TO_DB_REJECTED = "SAVE_FILEDATA_TO_DB_REJECTED";
export const GET_ALLFILES = "GET_ALLFILES";
export const GET_ALLFILES_FULFILLED = "GET_ALLFILES_FULFILLED";
export const GET_ALLFILES_REJECTED = "GET_ALLFILES_REJECTED";
export const SAVE_QB_FILEDATA_TO_DB = "SAVE_QB_FILEDATA_TO_DB";
export const SAVE_QB_FILEDATA_TO_DB_FULFILLED =
    "SAVE_QB_FILEDATA_TO_DB_FULFILLED";
export const SAVE_QB_FILEDATA_TO_DB_REJECTED =
    "SAVE_QB_FILEDATA_TO_DB_REJECTED";
export const SERVER_ERROR = "SERVER_ERROR";
export const SAVE_RC_ID = "SAVE_RC_ID";
export const SAVE_QP_ID = "SAVE_QP_ID";
export const SAVE_FC_ID = "SAVE_FC_ID";
export const SET_RD_STEP_1 = "SET_RD_STEP_1";
export const SET_RD_STEP_2 = "SET_RD_STEP_2";
export const SET_RD_STEP_3 = "SET_RD_STEP_3";
export const SET_RD_STEP_4 = "SET_RD_STEP_4";
export const FETCH_QUESTION_PAPER = "FETCH_QUESTION_PAPER";
export const FETCH_QUESTION_PAPER_FULFILLED = "FETCH_QUESTION_PAPER_FULFILLED";
export const FETCH_QUESTION_PAPER_REJECTED = "FETCH_QUESTION_PAPER_REJECTED";
export const FETCH_CANDIDATE_BY_RC_ID = "FETCH_CANDIDATE_BY_RC_ID";
export const FETCH_CANDIDATE_BY_RC_ID_FULFILLED =
    "FETCH_CANDIDATE_BY_RC_ID_FULFILLED";
export const FETCH_CANDIDATE_BY_RC_ID_REJECTED =
    "FETCH_CANDIDATE_BY_RC_ID_REJECTED";
export const FETCH_CANDIDATE = "FETCH_CANDIDATE";
export const FETCH_CANDIDATE_FULFILLED = "FETCH_CANDIDATE_FULFILLED";
export const FETCH_CANDIDATE_REJECTED = "FETCH_CANDIDATE_REJECTED";
export const FETCH_QUESTION_WITH_CATEGORY = "FETCH_QUESTION_WITH_CATEGORY";
export const FETCH_QUESTION_WITH_CATEGORY_FULFILLED =
    "FETCH_QUESTION_WITH_CATEGORY_FULFILLED";
export const FETCH_QUESTION_WITH_CATEGORY_REJECTED =
    "FETCH_QUESTION_WITH_CATEGORY_REJECTED";
export const FETCH_BINDED_QUESTIONS = "FETCH_BINDED_QUESTIONS";
export const FETCH_BINDED_QUESTIONS_FULFILLED =
    "FETCH_BINDED_QUESTIONS_FULFILLED";
export const FETCH_BINDED_QUESTIONS_REJECTED =
    "FETCH_BINDED_QUESTIONS_REJECTED";
export const SET_EDITABLE_QUESTIONPAPER_FORM =
    "SET_EDITABLE_QUESTIONPAPER_FORM";
export const FETCH_QUESTION_PAPER_FOR_BINDING =
    "FETCH_QUESTION_PAPER_FOR_BINDING";
export const FETCH_QUESTION_PAPER_FOR_BINDING_FULFILLED =
    "FETCH_QUESTION_PAPER_FOR_BINDING_FULFILLED";
export const FETCH_QUESTION_PAPER_FOR_BINDING_REJECTED =
    "FETCH_QUESTION_PAPER_FOR_BINDING_REJECTED";
export const FETCH_ALL_QUESTIONS_FOR_BIND = "FETCH_ALL_QUESTIONS_FOR_BIND";
export const FETCH_ALL_QUESTIONS_FOR_BIND_FULFILLED =
    "FETCH_ALL_QUESTIONS_FOR_BIND_FULFILLED";
export const FETCH_ALL_QUESTIONS_FOR_BIND_REJECTED =
    "FETCH_ALL_QUESTIONS_FOR_BIND_REJECTED";
export const HANDLE_CHECKED_QUESTIONS = "HANDLE_CHECKED_QUESTIONS";
export const SAVE_QUESTIONPAPER = "SAVE_QUESTIONPAPER";
export const SAVE_QUESTIONPAPER_FULFILLED = "SAVE_QUESTIONPAPER_FULFILLED";
export const SAVE_QUESTIONPAPER_REJECTED = "SAVE_QUESTIONPAPER_REJECTED";
export const FETCH_QUESTION_BY_CATEGORY_TYPE =
    "FETCH_QUESTION_BY_CATEGORY_TYPE";
export const FETCH_QUESTION_BY_CATEGORY_TYPE_FULFILLED =
    "FETCH_QUESTION_BY_CATEGORY_TYPE_FULFILLED";
export const FETCH_QUESTION_BY_CATEGORY_TYPE_REJECTED =
    "FETCH_QUESTION_BY_CATEGORY_TYPE_REJECTED";
export const GET_BINDED_QUESTIONS_BYID = "GET_BINDED_QUESTIONS_BYID";
export const GET_BINDED_QUESTIONS_BYID_FULFILLED =
    "GET_BINDED_QUESTIONS_BYID_FULFILLED";
export const GET_BINDED_QUESTIONS_BYID_REJECTED =
    "GET_BINDED_QUESTIONS_BYID_REJECTED";
export const MANAGE_NEW_QUESTIONPAPER = "MANAGE_NEW_QUESTIONPAPER";
export const SELECT_QUESTIONS = "SELECT_QUESTIONS";
export const EDIT_QUESTIONPAPER = "EDIT_QUESTIONPAPER";
export const EDIT_QUESTIONPAPER_FULFILLED = "EDIT_QUESTIONPAPER_FULFILLED";
export const EDIT_QUESTIONPAPER_REJECTED = "EDIT_QUESTIONPAPER_REJECTED";
export const DELETE_QUESTIONPAPER = "DELETE_QUESTIONPAPER";
export const DELETE_QUESTIONPAPER_FULFILLED = "DELETE_QUESTIONPAPER_FULFILLED";
export const DELETE_QUESTIONPAPER_REJECTED = "DELETE_QUESTIONPAPER_REJECTED";
export const FETCH_ALL_QUESTION_CATEGORIES = "FETCH_ALL_QUESTION_CATEGORIES";
export const FETCH_ALL_QUESTION_CATEGORIES_FULFILLED =
    "FETCH_ALL_QUESTION_CATEGORIES_FULFILLED";
export const FETCH_ALL_QUESTION_CATEGORIES_REJECTED =
    "FETCH_ALL_QUESTION_CATEGORIES_REJECTED";
export const DEACTIVATE_CANDIDATE = "DEACTIVATE_CANDIDATE";
export const SET_C_ITEM = "SET_C_ITEM";
export const CREATE_RECRUITMENT_DRIVE = "CREATE_RECRUITMENT_DRIVE";
export const CREATE_RECRUITMENT_DRIVE_FULFILLED =
    "CREATE_RECRUITMENT_DRIVE_FULFILLED";
export const CREATE_RECRUITMENT_DRIVE_REJECTED =
    "CREATE_RECRUITMENT_DRIVE_REJECTED";
export const UPDATE_RECRUITMENT_DRIVE = "UPDATE_RECRUITMENT_DRIVE";
export const UPDATE_RECRUITMENT_DRIVE_FULFILLED =
    "UPDATE_RECRUITMENT_DRIVE_FULFILLED";
export const UPDATE_RECRUITMENT_DRIVE_REJECTED =
    "UPDATE_RECRUITMENT_DRIVE_REJECTED";
export const FETCH_RECRUITMENT_DRIVE = "FETCH_RECRUITMENT_DRIVE";
export const FETCH_RECRUITMENT_DRIVE_FULFILLED =
    "FETCH_RECRUITMENT_DRIVE_FULFILLED";
export const FETCH_RECRUITMENT_DRIVE_REJECTED =
    "FETCH_RECRUITMENT_DRIVE_REJECTED";
export const RESET_DRIVE = "RESET_DRIVE";
export const SET_EDITABLE_RD = "SET_EDITABLE_RD";
export const HANDLE_RECRUITMENT_DRIVE = "HANDLE_RECRUITMENT_DRIVE";
export const HANDLE_RECRUITMENT_DRIVE_FULFILLED =
    "HANDLE_RECRUITMENT_DRIVE_FULFILLED";
export const HANDLE_RECRUITMENT_DRIVE_REJECTED =
    "HANDLE_RECRUITMENT_DRIVE_REJECTED";
export const SET_CURRENT_RD_FOR_EXAM = "SET_CURRENT_RD_FOR_EXAM";
export const FETCH_ALL_CANDIDATES_FOR_EXAM = "FETCH_ALL_CANDIDATES_FOR_EXAM";
export const FETCH_ALL_CANDIDATES_FOR_EXAM_FULFILLED =
    "FETCH_ALL_CANDIDATES_FOR_EXAM_FULFILLED";
export const FETCH_ALL_CANDIDATES_FOR_EXAM_REJECTED =
    "FETCH_ALL_CANDIDATES_FOR_EXAM_REJECTED";
export const FETCH_ALL_ANSWERS = "FETCH_ALL_ANSWERS";
export const FETCH_ALL_ANSWERS_FULFILLED = "FETCH_ALL_ANSWERS_FULFILLED";
export const FETCH_ALL_ANSWERS_REJECTED = "FETCH_ALL_ANSWERS_REJECTED";
export const FETCH_APPLICANTS_COUNT = "FETCH_APPLICANTS_COUNT";
export const FETCH_APPLICANTS_COUNT_FULFILLED =
    "FETCH_APPLICANTS_COUNT_FULFILLED";
export const FETCH_APPLICANTS_COUNT_REJECTED =
    "FETCH_APPLICANTS_COUNT_REJECTED";
export const FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS =
    "FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS";
export const FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS_FULFILLED =
    "FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS_FULFILLED";
export const FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS_REJECTED =
    "FETCH_ATTEMPTED_DESCRIPTIVE_ANSWERS_REJECTED";
export const SAVE_DESC_ANSWERS = "SAVE_DESC_ANSWERS";
export const SAVE_DESC_ANSWERS_FULFILLED = "SAVE_DESC_ANSWERS_FULFILLED";
export const SAVE_DESC_ANSWERS_REJECTED = "SAVE_DESC_ANSWERS_REJECTED";
export const SET_SAVE_DESC_ANS = "SET_SAVE_DESC_ANS";
export const SAVE_INTERVIEW_ROUND = "SAVE_INTERVIEW_ROUND";
export const SAVE_INTERVIEW_ROUND_FULFILLED = "SAVE_INTERVIEW_ROUND_FULFILLED";
export const SAVE_INTERVIEW_ROUND_REJECTED = "SAVE_INTERVIEW_ROUND_REJECTED";
export const HANDLE_ACTIVATION_OF_CANDIDATE = "HANDLE_ACTIVATION_OF_CANDIDATE";
export const HANDLE_ACTIVATION_OF_CANDIDATE_FULFILLED =
    "HANDLE_ACTIVATION_OF_CANDIDATE_FULFILLED";
export const HANDLE_ACTIVATION_OF_CANDIDATE_REJECTED =
    "HANDLE_ACTIVATION_OF_CANDIDATE_REJECTED";
export const FETCH_DIFFICULTY_COUNT = "FETCH_DIFFICULTY_COUNT";
export const FETCH_DIFFICULTY_COUNT_FULFILLED =
    "FETCH_DIFFICULTY_COUNT_FULFILLED";
export const FETCH_DIFFICULTY_COUNT_REJECTED =
    "FETCH_DIFFICULTY_COUNT_REJECTED";
export const FETCH_SUCCESS_RATIO = "FETCH_SUCCESS_RATIO";
export const FETCH_SUCCESS_RATIO_FULFILLED = "FETCH_SUCCESS_RATIO_FULFILLED";
export const FETCH_SUCCESS_RATIO_REJECTED = "FETCH_SUCCESS_RATIO_REJECTED";
export const FETCH_CANDIDATE_MARKS_FOR_CHART =
    "FETCH_CANDIDATE_MARKS_FOR_CHART";
export const FETCH_CANDIDATE_MARKS_FOR_CHART_FULFILLED =
    "FETCH_CANDIDATE_MARKS_FOR_CHART_FULFILLED";
export const FETCH_CANDIDATE_MARKS_FOR_CHART_REJECTED =
    "FETCH_CANDIDATE_MARKS_FOR_CHART_REJECTED";
export const FETCH_QUESTION_ANALYSIS_BY_CAT = "FETCH_QUESTION_ANALYSIS_BY_CAT";
export const FETCH_QUESTION_ANALYSIS_BY_CAT_FULFILLED =
    "FETCH_QUESTION_ANALYSIS_BY_CAT_FULFILLED";
export const FETCH_QUESTION_ANALYSIS_BY_CAT_REJECTED =
    "FETCH_QUESTION_ANALYSIS_BY_CAT_REJECTED";
export const FETCH_QUESTIONPAPER_DETAILS = "FETCH_QUESTIONPAPER_DETAILS";
export const FETCH_QUESTIONPAPER_DETAILS_FULFILLED =
    "FETCH_QUESTIONPAPER_DETAILS_FULFILLED";
export const FETCH_QUESTIONPAPER_DETAILS_REJECTED =
    "FETCH_QUESTIONPAPER_DETAILS_REJECTED";
export const DELETE_CANDIDATES_BY_RCID = "DELETE_CANDIDATES_BY_RCID";
export const DELETE_CANDIDATES_BY_RCID_FULFILLED =
    "DELETE_CANDIDATES_BY_RCID_FULFILLED";
export const DELETE_CANDIDATES_BY_RCID_REJECTED =
    "DELETE_CANDIDATES_BY_RCID_REJECTED";
export const SEND_MAIL = "SEND_MAIL";
export const SEND_MAIL_FULFILLED = "SEND_MAIL_FULFILLED";
export const SEND_MAIL_REJECTED = "SEND_MAIL_REJECTED";
export const SET_RDID_FOR_CANDIDATES_ANALYSIS = "SET_RDID_FOR_CANDIDATES_ANALYSIS";
export const SET_FLAG_FOR_CHART = "SET_FLAG_FOR_CHART";
export const CHANGE_ADMIN_PASSWORD = "CHANGE_ADMIN_PASSWORD";
export const CHANGE_ADMIN_PASSWORD_FULFILLED = "CHANGE_ADMIN_PASSWORD_FULFILLED";
export const CHANGE_ADMIN_PASSWORD_REJECTED = "CHANGE_ADMIN_PASSWORD_REJECTED";
export const ACTIVATE_OR_DEACTIVATE_ADMIN = "ACTIVATE_OR_DEACTIVATE_ADMIN";
export const ACTIVATE_OR_DEACTIVATE_ADMIN_FULFILLED = "ACTIVATE_OR_DEACTIVATE_ADMIN_FULFILLED";
export const ACTIVATE_OR_DEACTIVATE_ADMIN_REJECTED = "ACTIVATE_OR_DEACTIVATE_ADMIN_REJECTED";
export const SET_FETCHED_CANDIDATES_BYRCID = "SET_FETCHED_CANDIDATES_BYRCID";
export const BACK_UP_DB = "BACK_UP_DB";
export const BACK_UP_DB_FULFILLED = "BACK_UP_DB_FULFILLED";
export const BACK_UP_DB_REJECTED = "BACK_UP_DB_REJECTED";